name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases and pushing tags
      actions: write # Needed for allow changing the major and minor tags
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # For authentication
          # If you need to push to protected branches, use a PAT instead:
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "MAJOR=$(echo ${GITHUB_REF#refs/tags/v} | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "MINOR=$(echo ${GITHUB_REF#refs/tags/v} | cut -d. -f1,2)" >> $GITHUB_OUTPUT

      - name: Update major version tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa v${{ steps.get_version.outputs.MAJOR }} -m "Update v${{ steps.get_version.outputs.MAJOR }} tag"
          git tag -fa v${{ steps.get_version.outputs.MINOR }} -m "Update v${{ steps.get_version.outputs.MINOR }} tag"
          git status
          git push origin --tags --force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
